log:
  level: 'INFO'
global_path: '/media/home/data/all'
global_parameters:
  trajectory_history_window_length: 20
  trajectory_future_window_length: 30
data_process:
  input_path: 'dataset'
  output_path: 'internal'
  n_processes: 12
  visualize: False
  parameters:
    trajectory_min_history_window_length: 5
    object_trajectory_min_history_window_length: 5
    object_trajectory_min_future_window_length: 3
    object_distance_threshold: 100
    centerline_radius_scale: 3.0
    add_neighboring_lanes: True
    lane_radius_scale: 5.0
    min_lane_radius: 50.0
raster:
  data_process:
    input_path: '../storage/internal'
    output_path: '../storage/internal_graph'
    visualize: True
    debug_visualize: True
    parameters:
      agent_view_window_size: 224
      object_shape: [6, 6]
      centerline_point_shape: [6, 6]
      gauss_kernel_size: 25
      gauss_kernel_sigma: 4
  train:
    input_path: '../storage/internal_rasterized'
    output_path: 'model_storage/heatmap'
graph:
  data_process:
    input_path: 'internal'
    output_path: 'internal_graph'
    max_polyline_segments: 20
    max_polylines: 100
    normalization_parameter: 25.0
    visualize: False
    visualize_anchors: True
  train:
    train_input_path: '../../data/internal_graph/train'
    val_input_path: '../../data/internal_graph/val'
    output_path: 'model_storage/vectornet'
    visualize: True
    n_workers: int
    parameters:
      epochs: 20
      batch_size: 64
      n_targets: 20
      n_trajectories: 6
      tg_lr: 0.0001
      tg_sched_step: 10
      tg_sched_gamma: 0.1
      tf_lr: 0.0001
      tf_sched_step: 10
      tf_sched_gamma: 0.1
      huber_delta: 0.20
model:
  name: 'constant_velocity'
  config_path: 'configs/model_config.yaml'
evaluation:
  input_path: '../../data/internal_graph'
  output_path: '../../data/result'
  model_path: 'model_storage/vectornet'
  visualize: False
