log:
  level: 'INFO'
global_parameters:
  trajectory_history_window_length: 20
  trajectory_future_window_length: 30
data_process:
  input_path: '../sample1/train/sample1/'
  output_path: '../storage/internal/'
  visualize: True
  parameters:
    trajectory_min_history_window_length: 5
    object_trajectory_min_history_window_length: 5
    object_trajectory_min_future_window_length: 3
    object_distance_threshold: 100
    max_centerline_distance: 5
    add_neighboring_lanes: True
raster:
  data_process:
    input_path: '../storage/internal'
    output_path: '../storage/internal_graph'
    visualize: True
    debug_visualize: True
    parameters:
      agent_view_window_size: 224
      object_shape: [6, 6]
      centerline_point_shape: [6, 6]
      gauss_kernel_size: 25
      gauss_kernel_sigma: 4
  train:
    input_path: '../storage/internal_rasterized'
    output_path: 'model_storage/heatmap'
graph:
  data_process:
    input_path: '../storage/internal'
    output_path: '../storage/internal_graph'
    max_polyline_segments: 20
    max_polylines: 200
    normalization_parameter: 25.0
    visualize: True
  train:
    input_path: '../storage/internal_graph'
    output_path: '../storage/model_storage/vectornet'
    visualize: False
    parameters:
      epochs: 10
      n_targets: 6
      anchor_generator_lr: 0.0001
      anchor_generator_sched_step: 5
      anchor_generator_sched_gamma: 0.1
      trajectory_forecaster_lr: 0.001
      huber_delta: 0.16
model:
  name: 'constant_velocity'
  config_path: 'configs/model_config.yaml'
evaluation:
  input_path: '../storage/internal'
  output_path: '../storage/result'
  model_path: '../storage/model_storage/vectornet/model'
  visualize: True
