log:
  level: 'DEBUG'
global_parameters:
  trajectory_history_window_length: 20
  trajectory_future_window_length: 30
data_process:
  input_path: 'test_data/sample-test'
  output_path: 'test_data/internal'
  n_processes: 1
  visualize: True
  parameters:
    trajectory_min_history_window_length: 5
    object_trajectory_min_history_window_length: 5
    object_trajectory_min_future_window_length: 3
    object_distance_threshold: 100
    centerline_radius_scale: 3.0
    add_neighboring_lanes: True
    lane_radius_scale: 5.0
    min_lane_radius: 50.0
raster:
  data_process:
    input_path: 'test_data/internal'
    output_path: 'test_data/internal_raster'
    visualize: True
    debug_visualize: True
    parameters:
      agent_view_window_size: 224
      object_shape: [6, 6]
      centerline_point_shape: [6, 6]
      gauss_kernel_size: 25
      gauss_kernel_sigma: 4
      max_neighbours: 20
  train_tf:
    train_input_path: 'test_data/internal/train'
    val_input_path: 'test_data/internal/val'
    output_path: 'model_storage/heatmap_tf'
    model_name: 'home-tf-baseline'
    n_workers: 8
    parameters:
      epochs: 30
      lr: 0.01
      batch_size: 128
      sched_step: 10
      sched_gamma: 0.1
  train_heatmap:
    batch_size: 16
    n_workers: 8
    epochs: 30
    augmentation: True
    input_path: 'x'
    output_path: 'y'
graph:
  data_process:
    input_path: 'test_data/internal'
    output_path: 'test_data/internal_graph'
    max_polyline_segments: 20
    max_polylines: 300
    normalization_parameter: 25.0
    sampling_algorithm: 'polyline'
    visualize: True
    visualize_anchors: True
    visualize_candidate_centerlines: True
    report: True
  train:
    train_input_path: 'test_data/internal_graph/train'
    val_input_path: 'test_data/internal_graph/val'
    model_name: 'vectornet-testset-another-bs8'
    visualize: True
    n_workers: 8
    resume: True
    parameters:
      epochs: 150
      n_targets: 20
      n_trajectories: 6
      batch_size: 8
      tg_lr: 0.01
      tg_sched_step: 50
      tg_sched_gamma: 0.1
      tf_lr: 0.011
      tf_sched_step: 50
      tf_sched_gamma: 0.1
      huber_delta: 0.04
      use_traj_scoring: True
evaluation:
  input_path: 'test_data/internal_graph'
  output_path: 'test_data/result'
  visualize: True
